version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080" 
    environment:
      - POSTGRES_HOST=postgresDB
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    network_mode: "bot_api"